# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profileview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileview',
            name='response',
            field=models.IntegerField(choices=[(0, 'Like'), (1, 'skipped'), (2, 'SuperLike')]),
        ),
    ]
