# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170102_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermatch',
            unique_together=set([]),
        ),
    ]
