# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_gift_usergifts_virtualcurrency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermatch',
            unique_together=set([('user_to', 'user_from')]),
        ),
    ]
