# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20170110_2131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermatch',
            unique_together=set([]),
        ),
    ]
