# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20170110_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcurrency',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coins', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
