# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20170112_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergifts',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='profiles.Gift'),
        ),
        migrations.AlterField(
            model_name='usergifts',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergifts',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
