# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_userimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='icon',
            field=models.ImageField(upload_to='gifts'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.IntegerField(verbose_name='The price of the gift in terms of VirtualCurrency.'),
        ),
    ]
