# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0017_cardview'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardview',
            name='user_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardview',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
