# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
