# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 14:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161225_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
