# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161225_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='skipped',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='superlikes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
