# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161227_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='superlikes',
            field=models.IntegerField(default=0),
        ),
    ]
