# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161229_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None),
        ),
    ]
