# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aquarius',
            field=models.CharField(blank=True, choices=[(b'ar', b'Aries'), (b'ta', b'Taurus'), (b'ge', b'Gemini'), (b'ca', b'Cancer'), (b'le', b'Leo'), (b'vi', b'Virgo'), (b'li', b'Libra'), (b'sc', b'Scorpio'), (b'sa', b'Sagittarius'), (b'cp', b'Capricorn'), (b'aq', b'Aquarius'), (b'pi', b'Pisces')], max_length=4),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='drink',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='account',
            name='eye_color',
            field=models.CharField(blank=True, choices=[(b'bl', b'Black'), (b'br', b'Brown'), (b'bu', b'Blue')], max_length=4),
        ),
        migrations.AddField(
            model_name='account',
            name='hair_color',
            field=models.CharField(blank=True, choices=[(b'bl', b'Black'), (b'br', b'Brown')], max_length=4),
        ),
        migrations.AddField(
            model_name='account',
            name='height',
            field=models.FloatField(blank=True, default=5.8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='salary',
            field=models.FloatField(blank=True, default=1500000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='smoking',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='account',
            name='weed',
            field=models.NullBooleanField(),
        ),
    ]
