# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170112_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
