# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170112_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='oauth_id',
            field=models.CharField(default='12345six', max_length=100),
            preserve_default=False,
        ),
    ]
