# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_oauth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None),
        ),
    ]
