# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170116_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hair_color',
            field=models.CharField(blank=True, choices=[(b'bl', b'Black'), (b'br', b'Brown'), (b'bu', b'Blue')], max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[(b'S', b'Single'), (b'm', b'Married')], max_length=2),
        ),
    ]
