# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170205_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_instagram_activated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
