# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20170206_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='show_me_on_jar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='show_me_on_nearby',
            field=models.BooleanField(default=True),
        ),
    ]
