# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20170215_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='aquarius',
            field=models.CharField(blank=True, choices=[('ar', 'Aries'), ('ta', 'Taurus'), ('ge', 'Gemini'), ('ca', 'Cancer'), ('le', 'Leo'), ('vi', 'Virgo'), ('li', 'Libra'), ('sc', 'Scorpio'), ('sa', 'Sagittarius'), ('cp', 'Capricorn'), ('aq', 'Aquarius'), ('pi', 'Pisces')], max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('bl', 'Black'), ('br', 'Brown'), ('bu', 'Blue')], max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('bl', 'Black'), ('br', 'Brown'), ('bu', 'Blue')], max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('m', 'Married')], max_length=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('walk', 'Walk'), ('coffee', 'Coffee'), ('drink', 'Drink'), ('long_drive', 'Long Drive'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('detour', 'Detour'), ('movie', 'Movie')], max_length=20),
        ),
    ]
