# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20170401_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('coffee', 'Coffee'), ('detour', 'Detour'), ('movie', 'Catch A Movie'), ('bite', 'Grab A Bite'), ('run', 'Go For A Run'), ('out', 'Go Out'), ('drunk', 'Get Drunk')], max_length=20),
        ),
    ]
