# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_type', models.CharField(choices=[(b'match', b'User Match'), (b'like', b'Like'), (b'crush', b'Crush or Superlike'), (b'coins', b'Coins'), (b'view', b'Profile View'), (b'fj_team', b'FlirtJar Team')], default=b'fj_team', max_length=10)),
                ('notification_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
