# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_androiddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('match', 'User Match'), ('like', 'Like'), ('crush', 'Crush or Superlike'), ('coins', 'Coins'), ('view', 'Profile View'), ('fj_team', 'FlirtJar Team'), ('gift', 'Gift')], default='fj_team', max_length=10),
        ),
    ]
